version: '3.7'
services:
    app:
        container_name: web-machine-counter
        restart: always
        build: .
        ports:
            - '2002:2002'
        networks:
            - 'server'
networks:
    server:
        name: server
        driver: bridge